import type { FinanceState } from "./model";

// Datos mock del módulo Finanzas. Reemplazables por Supabase más adelante.

export const initialFinanceState: FinanceState = {
  daps: [
    {
      id: "dap-santander",
      banco: "Santander",
      titular: "Piero",
      tasa: 0.55,
      dias: 30,
      fechaRenovacion: "2026-06-20",
      valorRenovacion: 12_485_000,
      capitalVigente: 11_800_000,
      snapshots: [
        { date: "2026-02-20", value: 11_550_000 },
        { date: "2026-03-22", value: 11_614_000 },
        { date: "2026-04-21", value: 11_678_000 },
        { date: "2026-05-21", value: 12_170_000 },
        { date: "2026-06-20", value: 12_485_000 },
      ],
      movimientos: [
        {
          id: "dap1-m5",
          date: "2026-06-20",
          amount: 250_000,
          kind: "renovacion",
          label: "Renovación DAP Santander",
          detail: "Nuevo total $12.485.000 · 30 días · 0,55%",
          module: "dap",
          sourceId: "dap-santander",
          sourceName: "Santander",
        },
        {
          id: "dap1-m4",
          date: "2026-05-21",
          amount: 0,
          kind: "renovacion",
          label: "Renovación DAP Santander",
          detail: "Nuevo total $12.170.000 · 30 días · 0,55%",
          module: "dap",
          sourceId: "dap-santander",
          sourceName: "Santander",
        },
        {
          id: "dap1-m3",
          date: "2026-04-21",
          amount: 0,
          kind: "renovacion",
          label: "Renovación DAP Santander",
          detail: "Nuevo total $11.678.000 · 30 días · 0,55%",
          module: "dap",
          sourceId: "dap-santander",
          sourceName: "Santander",
        },
        {
          id: "dap1-m2",
          date: "2026-03-22",
          amount: 0,
          kind: "renovacion",
          label: "Renovación DAP Santander",
          detail: "Nuevo total $11.614.000 · 30 días · 0,55%",
          module: "dap",
          sourceId: "dap-santander",
          sourceName: "Santander",
        },
        {
          id: "dap1-m1",
          date: "2026-02-20",
          amount: 11_550_000,
          kind: "apertura",
          label: "Apertura DAP Santander",
          detail: "30 días · 0,55%",
          module: "dap",
          sourceId: "dap-santander",
          sourceName: "Santander",
        },
      ],
    },
    {
      id: "dap-bancoestado",
      banco: "BancoEstado",
      titular: "Consu",
      tasa: 1.6,
      dias: 90,
      fechaRenovacion: "2026-05-12",
      valorRenovacion: 6_230_000,
      capitalVigente: 6_000_000,
      snapshots: [
        { date: "2026-02-11", value: 6_000_000 },
        { date: "2026-05-12", value: 6_230_000 },
      ],
      movimientos: [
        {
          id: "dap2-m2",
          date: "2026-05-12",
          amount: 0,
          kind: "renovacion",
          label: "Renovación DAP BancoEstado",
          detail: "Nuevo total $6.230.000 · 90 días · 1,6%",
          module: "dap",
          sourceId: "dap-bancoestado",
          sourceName: "BancoEstado",
        },
        {
          id: "dap2-m1",
          date: "2026-02-11",
          amount: 6_000_000,
          kind: "apertura",
          label: "Apertura DAP BancoEstado",
          detail: "90 días · 1,6%",
          module: "dap",
          sourceId: "dap-bancoestado",
          sourceName: "BancoEstado",
        },
      ],
    },
  ],

  fintual: [
    {
      id: "fin-depa",
      nombre: "Depa",
      tipo: "grupal",
      bolsas: [
        { person: "Piero", depositado: 4_200_000 },
        { person: "Consu", depositado: 3_800_000 },
      ],
      variacion: 612_400,
      movimientos: [
        {
          id: "fd-m4",
          date: "2026-07-01",
          amount: 200_000,
          kind: "deposito",
          label: "Depósito · Depa",
          detail: "Bolsa Piero",
          module: "fintual",
          sourceId: "fin-depa",
          sourceName: "Depa",
          person: "Piero",
        },
        {
          id: "fd-m3",
          date: "2026-07-01",
          amount: 200_000,
          kind: "deposito",
          label: "Depósito · Depa",
          detail: "Bolsa Consu",
          module: "fintual",
          sourceId: "fin-depa",
          sourceName: "Depa",
          person: "Consu",
        },
        {
          id: "fd-m2",
          date: "2026-06-30",
          amount: 96_200,
          kind: "variacion",
          label: "Variación · Depa",
          detail: "Variación total +$612.400",
          module: "fintual",
          sourceId: "fin-depa",
          sourceName: "Depa",
        },
        {
          id: "fd-m1",
          date: "2026-06-02",
          amount: 200_000,
          kind: "deposito",
          label: "Depósito · Depa",
          detail: "Bolsa Piero",
          module: "fintual",
          sourceId: "fin-depa",
          sourceName: "Depa",
          person: "Piero",
        },
      ],
    },
    {
      id: "fin-viaje",
      nombre: "Viaje Asia",
      tipo: "grupal",
      bolsas: [
        { person: "Piero", depositado: 900_000 },
        { person: "Consu", depositado: 900_000 },
      ],
      variacion: -24_300,
      movimientos: [
        {
          id: "fv-m3",
          date: "2026-06-30",
          amount: -31_500,
          kind: "variacion",
          label: "Variación · Viaje Asia",
          detail: "Variación total −$24.300",
          module: "fintual",
          sourceId: "fin-viaje",
          sourceName: "Viaje Asia",
        },
        {
          id: "fv-m2",
          date: "2026-06-15",
          amount: 150_000,
          kind: "deposito",
          label: "Depósito · Viaje Asia",
          detail: "Bolsa Consu",
          module: "fintual",
          sourceId: "fin-viaje",
          sourceName: "Viaje Asia",
          person: "Consu",
        },
        {
          id: "fv-m1",
          date: "2026-06-15",
          amount: 150_000,
          kind: "deposito",
          label: "Depósito · Viaje Asia",
          detail: "Bolsa Piero",
          module: "fintual",
          sourceId: "fin-viaje",
          sourceName: "Viaje Asia",
          person: "Piero",
        },
      ],
    },
    {
      id: "fin-jubilacion",
      nombre: "Jubilación Piero",
      tipo: "personal",
      bolsas: [{ person: "Piero", depositado: 2_500_000 }],
      variacion: 181_700,
      movimientos: [
        {
          id: "fj-m2",
          date: "2026-06-30",
          amount: 42_100,
          kind: "variacion",
          label: "Variación · Jubilación Piero",
          detail: "Variación total +$181.700",
          module: "fintual",
          sourceId: "fin-jubilacion",
          sourceName: "Jubilación Piero",
        },
        {
          id: "fj-m1",
          date: "2026-06-05",
          amount: 100_000,
          kind: "deposito",
          label: "Depósito · Jubilación Piero",
          module: "fintual",
          sourceId: "fin-jubilacion",
          sourceName: "Jubilación Piero",
          person: "Piero",
        },
      ],
    },
  ],

  caja: {
    saldo: 737_500,
    movimientos: [
      {
        id: "cj-m5",
        date: "2026-07-05",
        amount: -42_500,
        kind: "gasto",
        label: "Ferretería",
        module: "caja",
        sourceName: "Caja casa",
      },
      {
        id: "cj-m4",
        date: "2026-07-03",
        amount: -85_000,
        kind: "gasto",
        label: "Gásfiter baño",
        module: "caja",
        sourceName: "Caja casa",
      },
      {
        id: "cj-m3",
        date: "2026-07-01",
        amount: 500_000,
        kind: "aporte",
        label: "Aporte a caja casa",
        detail: "Aporte mensual",
        module: "caja",
        sourceName: "Caja casa",
      },
      {
        id: "cj-m2",
        date: "2026-06-14",
        amount: -135_000,
        kind: "gasto",
        label: "Reparación lavadora",
        module: "caja",
        sourceName: "Caja casa",
      },
      {
        id: "cj-m1",
        date: "2026-06-01",
        amount: 500_000,
        kind: "aporte",
        label: "Aporte a caja casa",
        detail: "Aporte mensual",
        module: "caja",
        sourceName: "Caja casa",
      },
    ],
  },
};
